name: CI&CD

on:
  schedule:
    - cron: '30 2 * * 3' # Triggered by a schedule (every Wednesday at 2:30 AM), for automation.
    
  push:
    branches:
      - main
      - dev* # Triggered even by a branch starts with "dev*", "Dev*" or "DEV".
    tags:
      - '*' # with any tag
      
  pull_request:
    branches:
      - main
    tags:
      - '*'
env: # Create a environment to prevent error and warnings.
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GITHUB_ENV: ${{ github.workspace }}/.env

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3 # Checkout the through a GitHub Action

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20.x' # Configure the workflow by using Go version newer than 1.20

        # Set some environment variables
      - name: Build
        run: |
          set CGO_ENABLED=0 
          set GOOS=linux
          set GOARCH=amd64
          go build -o build/endpoint main.go

      - name: Test
        run:
          go test ./... # run the go test

  build:
    if: startsWith(github.ref, 'refs/tags/v') # Execute if there is a tag starts with "v"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write 
      #  Complete the identity challenge for the job with sigstore/fulcio when running outside of pull request.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install the cosign tool except on pull request
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@1a22e17968bb5f9192b82a39d3ffb322627f5169 # v4.0.1
        with:
          cosign-release: 'v2.0.2' 

      # https://github.com/docker/build-push-action
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@a946f06b5ddbde456d0115dc585e8dc3c7a0c3e0 # Newest since 11 May 2023

      # Login into Docker registry except on pull request
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@40891eba8c2bcd1309b07ba8b11232f313e86779 # Newest since 17 April 2023
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ENV: ${{ github.workspace }}/.env

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@c4ee3adeed93b1fa6a762f209fb01608c1a22f1e # Newest since 18 April 2023
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        env:
          IMAGES: ${{ steps.meta.outputs.tags }}
          GITHUB_ENV: ${{ github.workspace }}/.env

      # Build and push Docker image with Buildx (except on pull request)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@91df6b874e498451163feb47610c87c4a218c1ee # Newest since 11 May 2023
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type
